version: 2
enable-beta-ecosystems: true
updates:
- package-ecosystem: docker
  directory: "/cmd/csi_driver"
  schedule:
    interval: weekly
- package-ecosystem: gomod
  directory: "/"
  allow:
  - dependency-type: "all"
  schedule:
    interval: weekly
  groups:
    golang-x:
      patterns:
        - "golang.org/x*"
    google-golang:
      patterns:
        - "google.golang.org*"
    k8s-dependencies:
      patterns:
        - "k8s.io*"
        - "sigs.k8s.io*"
        - "github.com/kubernetes-csi*"
  open-pull-requests-limit: 10
- package-ecosystem: "helm"
  directory: "/helm/lustre-csi-driver"
  schedule:
    interval: "weekly"
