# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: preprov-pv-iam
spec:
  storageClassName: ""
  capacity:
    storage: 9000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    namespace: default
    name: preprov-pvc-iam
  csi:
    driver: lustre.csi.storage.gke.io
    volumeHandle: my-instance-iam # Modify this to use the project, zone, and mananged lustre instance name.
    volumeAttributes:
      ip: 172.17.1.6 # The IP address of the existing Lustre instance.
      filesystem: testlfs # The filesystem name of the existing Lustre instance.
      # Alternatively, you can use mountpoint:
      # mountpoint: ${EXISTING_LUSTRE_IP_ADDRESS}@tcp:/${EXISTING_LUSTRE_FSNAME}
      # If `mountpoint` is provided, it will override `ip` and `filesystem`.
      access_check_type: IAM
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: preprov-pvc-iam
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: preprov-pv-iam
  resources:
    requests:
      storage: 9000Gi