/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package upcall

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"k8s.io/klog/v2"
)

const (
	containerProxyPath = "/usr/bin/lustre-host-proxy"
	hostUdevDir        = "/host_etc_udev"
	hostProxyPath      = hostUdevDir + "/lustre-host-proxy"
	hostRulesPath      = hostUdevDir + "/rules.d/99-lustre.rules"

	udevRuleContent = `# Generated by Lustre CSI Driver Node Init. Do not edit.
SUBSYSTEM=="lustre", ACTION=="change", ENV{PARAM}=="?*", RUN+="/etc/udev/lustre-host-proxy /usr/sbin/lctl set_param $env{PARAM}=$env{SETTING}"
`
)

// SetupHostArtifacts deploys the static Go proxy binary and the udev rules to the host filesystem via the /host_etc_udev mount.
func SetupHostArtifacts() error {
	klog.Infof("Initializing Lustre upcall host artifacts via %s", hostUdevDir)

	// 1. Verify host mount exists.
	if _, err := os.Stat(hostUdevDir); err != nil {
		return fmt.Errorf("host udev mount directory %s missing or inaccessible: %w", hostUdevDir, err)
	}

	// 2. Copy the proxy binary from container to host.
	if err := copyFile(containerProxyPath, hostProxyPath); err != nil {
		return fmt.Errorf("failed to copy proxy binary to host: %w", err)
	}

	// 3. Make the host proxy executable.
	if err := os.Chmod(hostProxyPath, 0755); err != nil {
		return fmt.Errorf("failed to set executable permissions on host proxy: %w", err)
	}
	klog.Infof("Successfully installed host proxy binary at %s", hostProxyPath)

	// 4. Ensure rules.d directory exists on host.
	rulesDir := filepath.Dir(hostRulesPath)
	if err := os.MkdirAll(rulesDir, 0755); err != nil {
		return fmt.Errorf("failed to create host rules directory %s: %w", rulesDir, err)
	}

	// 5. Write the udev rules file
	if err := os.WriteFile(hostRulesPath, []byte(udevRuleContent), 0644); err != nil {
		return fmt.Errorf("failed to write udev rules to host at %s: %w", hostRulesPath, err)
	}
	klog.Infof("Successfully installed udev rules at %s", hostRulesPath)

	return nil
}

func copyFile(src, dst string) error {
	sourceFile, err := os.Open(src)
	if err != nil {
		return err
	}
	defer func() { _ = sourceFile.Close() }()

	destFile, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	if err != nil {
		return err
	}
	defer func() { _ = destFile.Close() }()

	if _, err = io.Copy(destFile, sourceFile); err != nil {
		return err
	}
	return destFile.Sync()
}
