name: presubmit

on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
        check-latest: true
    - name: Build CSI driver
      run: make driver
    - name: Build e2e test binary
      run: go build -mod=vendor ./test/k8s-integration
  
  unit-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
        check-latest: true
    - name: Test
      run: make unit-test
  
  sanity-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
        check-latest: true
    - name: Test
      run: make sanity-test
  
  verify:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
        check-latest: true
    - name: Verify
      run: make verify